case_manager_data:
  path: ''           # File path to the case manager data CSV file
  columns: ['assigned_at']                  # List of columns to specifically load from the CSV
  functions:                                # Functions to apply to specific columns
    assigned_at: ['most_recent_timestamp', 'oldest_timestamp']  # Functions applied to 'assigned_at'
  columns_to_keep: []                       # Columns to retain in the DataFrame after loading
  load_nrows: ''                            # Number of rows to load. Load all if empty or not present

osquery_data:
  path: ''              # File path to the osquery data CSV file
  columns: ['timestamp']                    # List of columns to specifically load from the CSV
  functions:                                # Functions to apply to specific columns
    timestamp: ['most_recent_timestamp', 'oldest_timestamp']    # Functions applied to 'assigned_at'
  columns_to_keep: []                       # Columns to retain in the DataFrame after loading
  load_nrows: ''                            # Number of rows to load. Load all if empty or not present

combined_case_query_data:
  path: './case_manager_query_data.csv'         # File path to the combined case query data CSV file
  load_nrows: '29000'                           # Only load two rows from this file
  summarize_query: true
  print_combined_case_query_data_frame: false
  generate_json_summary: true  # create JSON data objects summarizing different views of data   